/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.ws1314.a06;

import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author agribu
 */
public class Aufgabe06 extends javax.swing.JFrame {

    /**
     * Creates new form Aufgabe06
     */
    public Aufgabe06() {
        initComponents();
        postInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpInhalt = new javax.swing.JDesktopPane();
        ifWeinAufnehmen = new javax.swing.JInternalFrame();
        tpWeinAufnehmenTabs = new javax.swing.JTabbedPane();
        mbMenu = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        costumerMenu = new javax.swing.JMenu();
        addCostumerMenuItem = new javax.swing.JMenuItem();
        editCostumerMenuItem = new javax.swing.JMenuItem();
        deleteCostumerMenuItem = new javax.swing.JMenuItem();
        wineMenu = new javax.swing.JMenu();
        addWineMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        infoMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        ifWeinAufnehmen.setClosable(true);
        ifWeinAufnehmen.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        ifWeinAufnehmen.setIconifiable(true);
        ifWeinAufnehmen.setMaximizable(true);
        ifWeinAufnehmen.setResizable(true);
        ifWeinAufnehmen.setTitle("Wein aufnehmen");
        ifWeinAufnehmen.setVisible(true);

        javax.swing.GroupLayout ifWeinAufnehmenLayout = new javax.swing.GroupLayout(ifWeinAufnehmen.getContentPane());
        ifWeinAufnehmen.getContentPane().setLayout(ifWeinAufnehmenLayout);
        ifWeinAufnehmenLayout.setHorizontalGroup(
            ifWeinAufnehmenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpWeinAufnehmenTabs)
        );
        ifWeinAufnehmenLayout.setVerticalGroup(
            ifWeinAufnehmenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpWeinAufnehmenTabs)
        );

        dpInhalt.add(ifWeinAufnehmen);
        ifWeinAufnehmen.setBounds(20, 10, 670, 490);

        fileMenu.setMnemonic('D');
        fileMenu.setText("Datei");
        fileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuActionPerformed(evt);
            }
        });

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilities/icons/exit.png"))); // NOI18N
        exitMenuItem.setMnemonic('B');
        exitMenuItem.setText("Beenden");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        mbMenu.add(fileMenu);

        editMenu.setMnemonic('B');
        editMenu.setText("Bearbeiten");
        mbMenu.add(editMenu);

        costumerMenu.setMnemonic('K');
        costumerMenu.setText("Kunden");

        addCostumerMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        addCostumerMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilities/icons/add.png"))); // NOI18N
        addCostumerMenuItem.setMnemonic('A');
        addCostumerMenuItem.setText("Aufnehmen");
        addCostumerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCostumerMenuItemActionPerformed(evt);
            }
        });
        costumerMenu.add(addCostumerMenuItem);

        editCostumerMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        editCostumerMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilities/icons/stock_properties.png"))); // NOI18N
        editCostumerMenuItem.setMnemonic('e');
        editCostumerMenuItem.setText("Ändern");
        editCostumerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCostumerMenuItemActionPerformed(evt);
            }
        });
        costumerMenu.add(editCostumerMenuItem);

        deleteCostumerMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        deleteCostumerMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilities/icons/edit-delete.png"))); // NOI18N
        deleteCostumerMenuItem.setMnemonic('L');
        deleteCostumerMenuItem.setText("Löschen");
        costumerMenu.add(deleteCostumerMenuItem);

        mbMenu.add(costumerMenu);

        wineMenu.setMnemonic('W');
        wineMenu.setText("Wein");

        addWineMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        addWineMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilities/icons/add.png"))); // NOI18N
        addWineMenuItem.setMnemonic('A');
        addWineMenuItem.setText("Aufnehmen");
        addWineMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWineMenuItemActionPerformed(evt);
            }
        });
        wineMenu.add(addWineMenuItem);

        mbMenu.add(wineMenu);

        helpMenu.setMnemonic('?');
        helpMenu.setText("?");

        infoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        infoMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilities/icons/help-faq.png"))); // NOI18N
        infoMenuItem.setMnemonic('I');
        infoMenuItem.setText("Info");
        infoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(infoMenuItem);

        mbMenu.add(helpMenu);

        setJMenuBar(mbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpInhalt, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpInhalt, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        schliessfeldBetaetigt();
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void fileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileMenuActionPerformed

    private void addCostumerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCostumerMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCostumerMenuItemActionPerformed

    private void editCostumerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCostumerMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editCostumerMenuItemActionPerformed

    private void addWineMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addWineMenuItemActionPerformed
        ifWeinAufnehmen.setVisible(true);
    }//GEN-LAST:event_addWineMenuItemActionPerformed

    private void infoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoMenuItemActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        schliessfeldBetaetigt();
    }//GEN-LAST:event_formWindowClosing

    private void postInitComponents() {
        pWeinAufnehmen = new WeinAufnehmen();
        tpWeinAufnehmenTabs.addTab("Aufnehmen", pWeinAufnehmen);
    }
    
    private void closeWeinAufnehmen() {

        if (beenden() == JOptionPane.YES_OPTION) {
            return;
        }
        pWeinAufnehmen.setVisible(false);
        clearAll();
    }

    private void schliessfeldBetaetigt() {
        if (beenden() == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    private int beenden() {
        int antwort = JOptionPane.showConfirmDialog(
                this, "Wollen Sie wirklich das Fenster schließen?", "Fenster schließen.",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        return antwort;
    }

    public void clearAll() {
        dim = this.getSize();

        this.getContentPane().removeAll();
        initComponents();
        //pWeinAufnehmen.postInitComponents();

        this.setSize(dim);
    //aenderung.reset();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aufgabe06.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Aufgabe06().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addCostumerMenuItem;
    private javax.swing.JMenuItem addWineMenuItem;
    private javax.swing.JMenu costumerMenu;
    private javax.swing.JMenuItem deleteCostumerMenuItem;
    private javax.swing.JDesktopPane dpInhalt;
    private javax.swing.JMenuItem editCostumerMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JInternalFrame ifWeinAufnehmen;
    private javax.swing.JMenuItem infoMenuItem;
    private javax.swing.JMenuBar mbMenu;
    private javax.swing.JTabbedPane tpWeinAufnehmenTabs;
    private javax.swing.JMenu wineMenu;
    // End of variables declaration//GEN-END:variables

    private Dimension dim;
    private javax.swing.JPanel pWeinAufnehmen;
}
