/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui.ws1314.a06;

import java.awt.Toolkit;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.JTextComponent;
import javax.swing.text.PlainDocument;

/**
 *
 * @author agribu
 */
public class Start extends javax.swing.JFrame {

    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup = new javax.swing.ButtonGroup();
        contentDesktopPane = new javax.swing.JDesktopPane();
        addWineInternalFrame = new javax.swing.JInternalFrame();
        addWineTabbedPane = new javax.swing.JTabbedPane();
        addWinePanel1 = new gui.ws1314.a06.AddWinePanel();
        nullPanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        costumerMenu = new javax.swing.JMenu();
        addCostumerMenuItem = new javax.swing.JMenuItem();
        editCostumerMenuItem = new javax.swing.JMenuItem();
        deleteCostumerMenuItem = new javax.swing.JMenuItem();
        wineMenu = new javax.swing.JMenu();
        addWineMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        infoMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        addWineInternalFrame.setClosable(true);
        addWineInternalFrame.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        addWineInternalFrame.setIconifiable(true);
        addWineInternalFrame.setMaximizable(true);
        addWineInternalFrame.setResizable(true);
        addWineInternalFrame.setTitle("Wein anlegen");
        addWineInternalFrame.setVisible(false);

        addWineTabbedPane.addTab("Aufnehmen", addWinePanel1);

        javax.swing.GroupLayout nullPanelLayout = new javax.swing.GroupLayout(nullPanel);
        nullPanel.setLayout(nullPanelLayout);
        nullPanelLayout.setHorizontalGroup(
            nullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );
        nullPanelLayout.setVerticalGroup(
            nullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        addWineTabbedPane.addTab("", nullPanel);

        javax.swing.GroupLayout addWineInternalFrameLayout = new javax.swing.GroupLayout(addWineInternalFrame.getContentPane());
        addWineInternalFrame.getContentPane().setLayout(addWineInternalFrameLayout);
        addWineInternalFrameLayout.setHorizontalGroup(
            addWineInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addWineTabbedPane)
        );
        addWineInternalFrameLayout.setVerticalGroup(
            addWineInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addWineTabbedPane)
        );

        contentDesktopPane.add(addWineInternalFrame);
        addWineInternalFrame.setBounds(12, 12, 601, 537);
        contentDesktopPane.setLayer(addWineInternalFrame, javax.swing.JLayeredPane.DRAG_LAYER);

        fileMenu.setMnemonic('D');
        fileMenu.setText("Datei");
        fileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuActionPerformed(evt);
            }
        });

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilities/icons/exit.png"))); // NOI18N
        exitMenuItem.setMnemonic('B');
        exitMenuItem.setText("Beenden");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('B');
        editMenu.setText("Bearbeiten");
        menuBar.add(editMenu);

        costumerMenu.setMnemonic('K');
        costumerMenu.setText("Kunden");

        addCostumerMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        addCostumerMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilities/icons/add.png"))); // NOI18N
        addCostumerMenuItem.setMnemonic('A');
        addCostumerMenuItem.setText("Aufnehmen");
        addCostumerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCostumerMenuItemActionPerformed(evt);
            }
        });
        costumerMenu.add(addCostumerMenuItem);

        editCostumerMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        editCostumerMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilities/icons/stock_properties.png"))); // NOI18N
        editCostumerMenuItem.setMnemonic('e');
        editCostumerMenuItem.setText("Ändern");
        editCostumerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCostumerMenuItemActionPerformed(evt);
            }
        });
        costumerMenu.add(editCostumerMenuItem);

        deleteCostumerMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        deleteCostumerMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilities/icons/edit-delete.png"))); // NOI18N
        deleteCostumerMenuItem.setMnemonic('L');
        deleteCostumerMenuItem.setText("Löschen");
        costumerMenu.add(deleteCostumerMenuItem);

        menuBar.add(costumerMenu);

        wineMenu.setMnemonic('W');
        wineMenu.setText("Wein");

        addWineMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        addWineMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilities/icons/add.png"))); // NOI18N
        addWineMenuItem.setMnemonic('A');
        addWineMenuItem.setText("Aufnehmen");
        addWineMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWineMenuItemActionPerformed(evt);
            }
        });
        wineMenu.add(addWineMenuItem);

        menuBar.add(wineMenu);

        helpMenu.setMnemonic('?');
        helpMenu.setText("?");

        infoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        infoMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilities/icons/help-faq.png"))); // NOI18N
        infoMenuItem.setMnemonic('I');
        infoMenuItem.setText("Info");
        infoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(infoMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
       beenden();
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void addCostumerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCostumerMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCostumerMenuItemActionPerformed

    private void infoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoMenuItemActionPerformed

    private void fileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileMenuActionPerformed

    private void addWineMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addWineMenuItemActionPerformed
        addWineInternalFrame.setVisible(true);
    }//GEN-LAST:event_addWineMenuItemActionPerformed

    private void editCostumerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCostumerMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editCostumerMenuItemActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        beenden();
    }//GEN-LAST:event_formWindowClosing


    private void schliessfeldBetaetigt(java.awt.event.WindowEvent evt) {
        beenden();
    }

    private void beenden() {
        int antwort = JOptionPane.showConfirmDialog(
            this,"Wollen Sie wirklich das Fenster schließen?","Fenster schließen.",
            JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (antwort == JOptionPane.YES_OPTION) System.exit(0);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addCostumerMenuItem;
    private javax.swing.JInternalFrame addWineInternalFrame;
    private javax.swing.JMenuItem addWineMenuItem;
    private gui.ws1314.a06.AddWinePanel addWinePanel1;
    private javax.swing.JTabbedPane addWineTabbedPane;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JDesktopPane contentDesktopPane;
    private javax.swing.JMenu costumerMenu;
    private javax.swing.JMenuItem deleteCostumerMenuItem;
    private javax.swing.JMenuItem editCostumerMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem infoMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel nullPanel;
    private javax.swing.JMenu wineMenu;
    // End of variables declaration//GEN-END:variables
}
